from codes import Rewards

WALL = Rewards.WALL
CELL = Rewards.CELL
OBJECTIVE = Rewards.OBJECTIVE

# Not using the codes themselves here makes it easier to visualize it
test_map = [
    # 0     #1    #2    #3    #4    #5    #6    #7    #8    #9    #10
    [WALL, WALL, WALL, WALL, WALL,  100, WALL, WALL, WALL, WALL, WALL],  # 0
    [WALL, CELL, CELL, CELL, CELL, CELL, CELL, CELL, CELL, OBJECTIVE, WALL],  # 1
    [WALL, CELL, WALL, WALL, WALL, WALL, WALL, CELL, WALL, CELL, WALL],  # 2
    [WALL, CELL, CELL, CELL, CELL, CELL, CELL, CELL, WALL, CELL, WALL],  # 3
    [WALL, WALL, WALL, CELL, WALL, WALL, WALL, CELL, WALL, WALL, WALL],  # 4
    [CELL, CELL, CELL, CELL, CELL, CELL, CELL, CELL, CELL, CELL, CELL],  # 5
    [WALL, WALL, WALL, WALL, WALL, CELL, WALL, WALL, WALL, WALL, WALL],  # 6
    [WALL, CELL, CELL, CELL, CELL, CELL, CELL, CELL, CELL, CELL, WALL],  # 7
    [WALL, WALL, WALL, CELL, WALL, WALL, WALL, CELL, WALL, WALL, WALL],  # 8
    [CELL, CELL, CELL, CELL, CELL, CELL, CELL, CELL, CELL, CELL, CELL],  # 9
    [WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL]  # 10
]

validation_map = [
    #  0    #1    #2    #3    #4    #5    #6    #7    #8    #9    #10   #11   #12   #13
    [WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL],       # 0
    [WALL, CELL, CELL, CELL, CELL, WALL, CELL, CELL, CELL, CELL, CELL, CELL, WALL, WALL],       # 1
    [WALL, CELL, WALL, CELL, CELL, CELL, CELL, CELL, CELL, CELL, CELL, CELL, WALL, WALL],       # 2
    [WALL, WALL, CELL, WALL, CELL, CELL, CELL, WALL, CELL, WALL, WALL, CELL, CELL, WALL],       # 3
    [WALL, CELL, WALL, CELL, CELL, CELL, CELL, CELL, CELL, WALL, CELL, CELL, CELL, WALL],       # 4
    [WALL, CELL, CELL, CELL, CELL, CELL, CELL, CELL, CELL, CELL, CELL, CELL, OBJECTIVE, WALL],  # 5
    [WALL, WALL, WALL, WALL, WALL, CELL, CELL, WALL, CELL, WALL, WALL, WALL, WALL, WALL],       # 6
    [WALL, WALL, WALL, WALL, WALL, CELL, CELL, CELL, CELL, WALL, WALL, WALL, WALL, WALL],       # 7
    [WALL, WALL, WALL, WALL, WALL, CELL, CELL, CELL, CELL, WALL, WALL, WALL, WALL, WALL],       # 8
    [WALL, WALL, WALL, WALL, WALL, CELL, CELL, WALL, CELL, WALL, WALL, WALL, WALL, WALL],       # 9
    [WALL, WALL, WALL, WALL, WALL, CELL, CELL, CELL, CELL, WALL, WALL, WALL, WALL, WALL],       # 10
    [WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL]        # 11
]
